/**
 * Mapping of specific opening names to their ECO codes.
 * This helps detect rare and specific openings that might not be caught by general patterns.
 */
export const SPECIFIC_OPENING_MAP: Record<string, string> = {
  // Rare gambits and offbeat openings
  englund: "A40",
  "englund gambit": "A40",
  rousseau: "C50",
  "rousseau gambit": "C50",
  "blackmar-diemer": "D00",
  "blackmar diemer": "D00",
  "benko gambit": "A57",
  "volga gambit": "A57",
  "budapest gambit": "A51",
  "albin countergambit": "D08",
  "from's gambit": "A02",
  "staunton gambit": "A82",
  "elephant gambit": "C40",
  "latvian gambit": "C40",
  "king's gambit": "C30",
  "kings gambit": "C30",
  "evans gambit": "C51",
  "danish gambit": "C21",
  "halloween gambit": "C46",
  "muzio gambit": "C53",
  "scotch gambit": "C44",
  "vienna gambit": "C25",
  "wing gambit": "C00",
  "blumenfeld countergambit": "E10",
  "polovodin gambit": "E12",
  "spassky gambit": "E08",
  "hungarian gambit": "E00",
  "devin gambit": "E00",
  "polugaevsky gambit": "E17",
  "taimanov gambit": "E17",
  "averbakh gambit": "E30",
  "vitolins-adorjan gambit": "E32",
  "belyavsky gambit": "E34",
  "adorjan gambit": "E60",
  "leko gambit": "E60",
  "florentine gambit": "E77",
  "sämisch gambit": "E81",
  "kozul gambit": "E98",
  "shocron gambit": "E21",
  "romanovsky gambit": "E23",
  "dus-khotimirsky": "E10",
  "spielmann variation": "E10",
  "birmingham gambit": "A00",
  bugayev: "A00",
  "tartakower gambit": "A00",
  "wolferts gambit": "A00",
  "schuehler gambit": "A00",
  "schiffler-sokolsky": "A00",
  karniewski: "A00",
  grigorian: "A00",
  "german defense": "A00",
  "czech defense": "A00",
  "baltic defense": "A00",
  outflank: "A00",
  "queenside defense": "A00",
  "rooks swap": "A00",
  "king's indian variation": "A00",
  "sokolsky attack": "A00",
  "schiffler attack": "A00",
  "myers variation": "A00",
  "gent gambit": "A00",
  "paris gambit": "A00",
  "amar gambit": "A00",
  "polish gambit": "A00",
  "spike lee gambit": "A00",
  "kádas gambit": "A00",
  "schneider gambit": "A00",
  "steinbok gambit": "A00",
  "alessi gambit": "A00",
  "coca-cola gambit": "A00",
  "grob gambit": "A00",
  "basman gambit": "A00",
  "fritz gambit": "A00",
  "romford countergambit": "A00",
  "keres gambit": "A00",
  "richter-grob gambit": "A00",
  "zilbermints gambit": "A00",
  "zilbermints-hartlaub gambit": "A00",
  "zilbermints variation": "D00",
  "van kuijk gambit": "A00",
  "winterberg gambit": "A00",
  "pachman gambit": "A00",
  "brooklyn benko gambit": "A00",
  "reversed alekhine": "A00",
  "reversed brooklyn": "A00",
  "reversed french": "A00",
  "reversed krebs": "A00",
  "reversed mokele mbembe": "A00",
  "reversed norwegian": "A00",
  "reversed modern": "A00",
  "reversed philidor": "C00",
  "reversed rat": "A00",
  "reversed albin": "D00",
  "barnes opening": "A00",
  "fool's mate": "A00",
  "gedult gambit": "A00",
  hammerschlag: "A00",
  "clemenz opening": "A00",
  "crab opening": "A00",
  "creepy crawly": "A00",
  hippopotamus: "A00",
  "shy attack": "A00",
  "global opening": "A00",
  "grob opening": "A00",
  "hungarian opening": "A00",
  "kádas opening": "A00",
  "lasker simul special": "A00",
  "mieses opening": "A00",
  "polish opening": "A00",
  "saragossa opening": "A00",
  "sodium attack": "A00",
  "valencia opening": "A00",
  "van geet opening": "A00",
  "anderssen's opening": "A00",
  "amsterdam attack": "A00",
  "barnes defense": "B00",
  "borg defense": "B00",
  "carr defense": "B00",
  "duras gambit": "B00",
  "fried fox": "B00",
  "goldsmith defense": "B00",
  picklepuss: "B00",
  "guatemala defense": "B00",
  "lemming defense": "B00",
  "lion defense": "B00",
  "lion's jaw": "B00",
  "nimzowitsch defense": "B00",
  "el columpio": "B00",
  "colorado countergambit": "B00",
  "french connection": "B00",
  "hornung gambit": "B00",
  "kennedy variation": "B00",
  "bielefelder gambit": "B00",
  "hammer gambit": "B00",
  "herford gambit": "B00",
  "keres attack": "B00",
  linksspringer: "B00",
  "paulsen attack": "B00",
  "riemann defense": "B00",
  "de smet gambit": "B00",
  "mikenas variation": "B00",
  "neo-mongoloid": "B00",
  "pirc connection": "B00",
  "pseudo-spanish": "B00",
  "scandinavian variation": "B00",
  "aachen gambit": "B00",
  "advance variation": "B00",
  "bogoljubov variation": "B00",
  "brandics gambit": "B00",
  "erben gambit": "B00",
  "heinola-deppe gambit": "B00",
  "nimzowitsch gambit": "B00",
  "richter gambit": "B00",
  "vehre variation": "B00",
  "exchange variation": "B00",
  "marshall gambit": "B00",
  "wheeler gambit": "B00",
  "williams variation": "B00",
  "woodchuck variation": "B00",
  "owen defense": "B00",
  "hekili-loa gambit": "B00",
  "matovinsky gambit": "B00",
  "naselwaus gambit": "B00",
  "smith gambit": "B00",
  "unicorn variation": "B00",
  "wind gambit": "B00",
  "pirc defense": "B07",
  "rat defense": "B00",
  "antal defense": "B00",
  "fuller gambit": "B00",
  harmonist: "B00",
  "petruccioli attack": "B00",
  "spike attack": "B00",
  "st. george defense": "B00",
  "san jorge variation": "B00",
  "ware defense": "B00",
  snagglepuss: "B00",
  "berlin gambit": "B00",
  "scandinavian defense": "B01",
  "anderssen counterattack": "B01",
  "goteborg system": "B01",
  "orthodox attack": "B01",
  "blackburne gambit": "B01",
  "blackburne-kloosterboer": "B01",
  "boehnke gambit": "B01",
  "bronstein variation": "B01",
  "classical variation": "B01",
  "grünfeld variation": "B01",
  "gubinsky-melts": "B01",
  "icelandic-palme gambit": "B01",
  "kiel variation": "B01",
  "kloosterboer gambit": "B01",
  "alekhine defense": "B02",
  "modern defense": "B06",
  "robatsch defense": "B06",
  "old benoni": "A43",
  "benoni defense": "A56",
  "modern benoni": "A60",
  "old indian": "A53",
  "catalan opening": "E00",
  "bogo-indian": "E11",
  "queen's indian": "E12",
  "nimzo-indian": "E20",
  "king's indian": "E60",
  "grünfeld defense": "D80",
  "dutch defense": "A80",
  "london system": "D02",
  "colle system": "D04",
  "torre attack": "D03",
  "queen's gambit": "D30",
  "queens gambit": "D30",
  qgd: "D30",
  "slav defense": "D10",
  "semi-slav": "D43",
  semislav: "D43",
  "queen's gambit accepted": "D20",
  "queens gambit accepted": "D20",
  qga: "D20",
  "ruy lopez": "C60",
  spanish: "C60",
  "italian game": "C50",
  "giuoco piano": "C50",
  "two knights": "C55",
  "four knights": "C46",
  "three knights": "C46",
  "scotch game": "C44",
  ponziani: "C44",
  philidor: "C41",
  petrov: "C42",
  "vienna game": "C25",
  "bishop's opening": "C23",
  "center game": "C22",
  "french defense": "C00",
  "caro-kann": "B10",
  "sicilian defense": "B20",
  "english opening": "A10",
  "reti opening": "A04",
  "king's indian attack": "A07",
  "kings indian attack": "A07",
  "bird opening": "A02",
  "larsen's opening": "A01",
  "larsen opening": "A01",
  "nimzowitsch-larsen": "A01",
  "nimzo-larsen": "A01",
  "nimzo larsen": "A01",
  "zukertort opening": "A04",
  zukertort: "A04",
  "hartlaub-charlick": "A40",
  "hartlaub charlick": "A40",
  "blackburne-kostić": "C50",
  "blackburne kostić": "C50",
  "blackburne-kostic": "C50",
  "blackburne kostic": "C50",
  "nyezhmetdinov-rossolimo": "B30",
  "nyezhmetdinov rossolimo": "B30",
  "dragon variation": "B70",
  dragon: "B70",
  "van't kruijs": "A00",
  "dunst opening": "A00",
  "ware opening": "A00",
  "sokolsky opening": "A00",
};
