
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async screenCapture() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("screen_capture") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async findFidePlayer(player: string) : Promise<Result<FidePlayer | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("find_fide_player", { player }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async fetchFideProfileHtml(fideId: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_fide_profile_html", { fideId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Save a FIDE profile photo (either from URL or base64 data) to local storage
 * Returns the local file path
 */
async saveFidePhoto(fideId: string, photoData: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_fide_photo", { fideId, photoData }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get best moves from the engine for a given position and options.
 */
async getBestMoves(id: string, engine: string, tab: string, goMode: GoMode, options: EngineOptions) : Promise<Result<[number, BestMoves[]] | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_best_moves", { id, engine, tab, goMode, options }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Analyze a game using the engine, returning move-by-move analysis.
 */
async analyzeGame(id: string, engine: string, goMode: GoMode, options: AnalysisOptions, uciOptions: EngineOption[]) : Promise<Result<MoveAnalysis[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("analyze_game", { id, engine, goMode, options, uciOptions }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stop a specific engine process (without killing it) by engine name and tab.
 */
async stopEngine(engine: string, tab: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_engine", { engine, tab }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Kill a specific engine process by engine name and tab.
 * FIXED: Always remove from map to prevent memory leaks
 */
async killEngine(engine: string, tab: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("kill_engine", { engine, tab }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Kill all engine processes associated with a given tab.
 * FIXED: Proper error handling to prevent zombie processes
 */
async killEngines(tab: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("kill_engines", { tab }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Retrieve logs for a specific engine process.
 */
async getEngineLogs(engine: string, tab: string) : Promise<Result<EngineLog[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_engine_logs", { engine, tab }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async memorySize() : Promise<bigint> {
    return await TAURI_INVOKE("memory_size");
},
/**
 * Gets a random puzzle from the database within the specified rating range
 * 
 * This function uses a cache to avoid repeated database queries. The cache is
 * refreshed when it's empty, when the rating range changes, or when all puzzles
 * in the cache have been used.
 * 
 * # Arguments
 * * `file` - Path to the puzzle database
 * * `min_rating` - Minimum puzzle rating to include
 * * `max_rating` - Maximum puzzle rating to include
 * * `random` - Randomize puzzle in cache
 * * `themes` - Optional list of themes to filter by (puzzle must contain at least one)
 * * `opening_tags` - Optional list of opening tags to filter by (puzzle must contain at least one)
 * 
 * # Returns
 * * `Ok(Puzzle)` if a puzzle was found
 * * `Err(Error::NoPuzzles)` if no puzzles match the criteria
 * * Other errors if there was a problem accessing the database
 */
async getPuzzle(file: string, minRating: number, maxRating: number, random: boolean, themes: string[] | null, openingTags: string[] | null) : Promise<Result<Puzzle, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_puzzle", { file, minRating, maxRating, random, themes, openingTags }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async searchOpeningName(query: string) : Promise<Result<OutOpening[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_opening_name", { query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getOpeningFromFen(fen: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_opening_from_fen", { fen }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getOpeningFromName(name: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_opening_from_name", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getOpeningInfoFromFen(fen: string) : Promise<Result<OpeningInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_opening_info_from_fen", { fen }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getPlayersGameInfo(file: string, id: number) : Promise<Result<PlayerGameInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_players_game_info", { file, id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Query a UCI engine for its configuration (name and options).
 * FIXED: Proper process cleanup with timeout to prevent zombie processes
 */
async getEngineConfig(path: string) : Promise<Result<EngineConfig, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_engine_config", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async fileExists(path: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("file_exists", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getFileMetadata(path: string) : Promise<Result<FileMetadata, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_file_metadata", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async mergePlayers(file: string, player1: number, player2: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("merge_players", { file, player1, player2 }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async convertPgn(file: string, dbPath: string, timestamp: number | null, title: string, description: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("convert_pgn", { file, dbPath, timestamp, title, description }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async initProfileDb(dbPath: string, title: string, description: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("init_profile_db", { dbPath, title, description }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getPlayer(file: string, id: number) : Promise<Result<Player | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_player", { file, id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async countPgnGames(file: string) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("count_pgn_games", { file }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async readGames(file: string, start: number, end: number) : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_games", { file, start, end }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async lexPgn(pgn: string) : Promise<Result<Token[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("lex_pgn", { pgn }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async isBmi2Compatible() : Promise<boolean> {
    return await TAURI_INVOKE("is_bmi2_compatible");
},
async deleteGame(file: string, n: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_game", { file, n }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteDuplicatedGames(file: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_duplicated_games", { file }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteEmptyGames(file: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_empty_games", { file }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Clear the in-memory game cache to free memory
 * FIXED: Also clear position search cache to prevent unbounded growth
 */
async clearGames() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_games") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setFileAsExecutable(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_file_as_executable", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteIndexes(file: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_indexes", { file }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createIndexes(file: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_indexes", { file }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async editDbInfo(file: string, title: string | null, description: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("edit_db_info", { file, title, description }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setProfileMetadata(file: string, key: string, value: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_profile_metadata", { file, key, value }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteDbGame(file: string, gameId: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_db_game", { file, gameId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a database file and cleanup resources
 * OPTIMIZED: Removed PRAGMA optimize (unnecessary before deletion), reduced wait times, and close connections first
 */
async deleteDatabase(file: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_database", { file }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Optimize a database: create indexes, run ANALYZE, apply pragmas, and update Lichess tournament events.
 */
async optimizeDatabase(file: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("optimize_database", { file }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async exportToPgn(file: string, destFile: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_to_pgn", { file, destFile }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async exportPositionGamesToPgn(file: string, fen: string, destFile: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_position_games_to_pgn", { file, fen, destFile }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async exportSelectedGamesToPgn(file: string, gameIds: number[], destFile: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_selected_games_to_pgn", { file, gameIds, destFile }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async authenticate(username: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("authenticate", { username }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async writeGame(file: string, n: number, pgn: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("write_game", { file, n, pgn }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async downloadFideDb() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download_fide_db") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async downloadFile(id: string, url: string, path: string, token: string | null, finalize: boolean | null, totalSize: number | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download_file", { id, url, path, token, finalize, totalSize }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTournaments(file: string, query: TournamentQuery) : Promise<Result<QueryResponse<Event[]>, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_tournaments", { file, query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDbInfo(file: string) : Promise<Result<DatabaseInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_db_info", { file }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getGames(file: string, query: GameQueryJs) : Promise<Result<QueryResponse<NormalizedGame[]>, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_games", { file, query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getGame(file: string, gameId: number) : Promise<Result<NormalizedGame, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_game", { file, gameId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateGame(file: string, gameId: number, update: UpdateGame) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_game", { file, gameId, update }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * ============================================================================
 * Search for chess positions in the database
 * Returns position statistics and matching games
 * ============================================================================
 */
async searchPosition(file: string, query: GameQueryJs, tabId: string) : Promise<Result<[PositionStats[], NormalizedGame[]], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_position", { file, query, tabId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Pre-cache openings from TSV files
 * This function reads all opening TSV files, converts PGN to FEN,
 * searches for each position in the database, and caches the results
 */
async precacheOpenings(databasePath: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("precache_openings", { databasePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importOnlineTournament(url: string, title: string | null, description: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_online_tournament", { url, title, description }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Download pre-calculated position cache database
 */
async downloadPositionCache() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download_position_cache") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setDbSource(file: string, source: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_db_source", { file, source }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDbSource(file: string) : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_db_source", { file }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async mergeProfileEventFromDbPlayer(profileDbFile: string, sourceDbFile: string, playerId: number, eventName: string) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("merge_profile_event_from_db_player", { profileDbFile, sourceDbFile, playerId, eventName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getPlayers(file: string, query: PlayerQuery) : Promise<Result<QueryResponse<Player[]>, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_players", { file, query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Gets information about a puzzle database
 * 
 * This function retrieves metadata about a puzzle database, including:
 * - The title (derived from the filename)
 * - The number of puzzles in the database
 * - The size of the database file
 * - The full path to the database file
 * 
 * # Arguments
 * * `file` - Relative path to the puzzle database within the app's data directory
 * * `app` - Tauri app handle used to resolve the full path
 * 
 * # Returns
 * * `Ok(PuzzleDatabaseInfo)` with the database information
 * * `Err(Error)` if there was a problem accessing the database or file
 */
async getPuzzleDbInfo(file: string) : Promise<Result<PuzzleDatabaseInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_puzzle_db_info", { file }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Gets the minimum and maximum rating range from a puzzle database
 * 
 * This function queries the database to find the lowest and highest puzzle ratings.
 * 
 * # Arguments
 * * `file` - Path to the puzzle database
 * 
 * # Returns
 * * `Ok((min_rating, max_rating))` with the rating range
 * * `Err(Error)` if there was a problem accessing the database
 */
async getPuzzleRatingRange(file: string) : Promise<Result<[number, number], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_puzzle_rating_range", { file }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Imports puzzles from a local file into a new puzzle database
 * 
 * This function can handle different types of puzzle files:
 * - PGN files containing puzzles (with FEN positions and solution moves)
 * - Existing puzzle database files (.db, .db3)
 * - Compressed files (.zst)
 * 
 * # Arguments
 * * `source_file` - Path to the source puzzle file
 * * `db_path` - Path where the new puzzle database should be created
 * * `title` - Title for the puzzle database
 * * `description` - Optional description for the puzzle database
 * * `app` - Tauri app handle for progress events
 * 
 * # Returns
 * * `Ok(())` if import was successful
 * * `Err(Error)` if there was a problem importing the file
 */
async importPuzzleFile(sourceFile: string, dbPath: string, title: string, description: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_puzzle_file", { sourceFile, dbPath, title, description }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Checks if a puzzle database has the themes and opening_tags columns
 * 
 * # Arguments
 * * `file` - Path to the puzzle database
 * 
 * # Returns
 * * `Ok((has_themes, has_opening_tags))` indicating which columns exist
 * * `Err(Error)` if there was a problem accessing the database
 */
async checkPuzzleDbColumns(file: string) : Promise<Result<[boolean, boolean], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_puzzle_db_columns", { file }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Gets distinct values for themes from a puzzle database
 * OPTIMIZED: Uses normalized table if available, otherwise falls back to old method
 * 
 * # Arguments
 * * `file` - Path to the puzzle database
 * 
 * # Returns
 * * `Ok(Vec<ThemeOption>)` with distinct theme values and their friendly names
 * * `Err(Error)` if there was a problem accessing the database
 */
async getPuzzleThemes(file: string) : Promise<Result<ThemeGroup[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_puzzle_themes", { file }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Gets distinct values for opening_tags from a puzzle database
 * OPTIMIZED: Uses normalized table if available, otherwise falls back to old method
 * 
 * # Arguments
 * * `file` - Path to the puzzle database
 * 
 * # Returns
 * * `Ok(Vec<OpeningTagOption>)` with distinct opening tag values and their friendly names
 * * `Err(Error)` if there was a problem accessing the database
 */
async getPuzzleOpeningTags(file: string) : Promise<Result<OpeningTagOption[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_puzzle_opening_tags", { file }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Validates a downloaded puzzle database file
 */
async validatePuzzleDatabase(file: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("validate_puzzle_database", { file }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async checkPackageManagerAvailable(manager: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_package_manager_available", { manager }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async installPackage(manager: string, packageName: string) : Promise<Result<PackageManagerResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("install_package", { manager, packageName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async checkPackageInstalled(manager: string, packageName: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_package_installed", { manager, packageName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async findExecutablePath(executableName: string) : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("find_executable_path", { executableName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getVariantPosition(fen: string, engine: string) : Promise<Result<VariantPosition | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_variant_position", { fen, engine }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async upsertVariantPosition(fen: string, engine: string, recommendedMove: string, ms: bigint) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("upsert_variant_position", { fen, engine, recommendedMove, ms }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async generatePuzzleVariantsFromTree(root: PuzzleTreeNodeDto, orientation: string, selectedDepth: number) : Promise<Result<GeneratePuzzleVariantsResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("generate_puzzle_variants_from_tree", { root, orientation, selectedDepth }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async buildVariantsTree(request: BuildVariantsTreeRequest) : Promise<Result<BuildVariantsTreeResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("build_variants_tree", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async analysisDbSetAnalyzedGame(gameId: string, analyzedPgn: string, profileId: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("analysis_db_set_analyzed_game", { gameId, analyzedPgn, profileId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async analysisDbGetAnalyzedGame(gameId: string, profileId: string | null) : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("analysis_db_get_analyzed_game", { gameId, profileId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async analysisDbGetAllAnalyzedGames(profileId: string | null) : Promise<Result<AnalyzedGameEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("analysis_db_get_all_analyzed_games", { profileId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async analysisDbSetGameStats(gameId: string, stats: StoredGameStats, profileId: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("analysis_db_set_game_stats", { gameId, stats, profileId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async analysisDbGetGameStats(gameId: string, profileId: string | null) : Promise<Result<StoredGameStats | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("analysis_db_get_game_stats", { gameId, profileId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async analysisDbGetGameStatsBulk(gameIds: string[], profileId: string | null) : Promise<Result<GameStatsEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("analysis_db_get_game_stats_bulk", { gameIds, profileId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async analysisDbDeleteEntries(gameIds: string[], profileId: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("analysis_db_delete_entries", { gameIds, profileId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async analysisDbClearAnalyzedPgns() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("analysis_db_clear_analyzed_pgns") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async analysisDbGetAnalyzedGamesBulk(gameIds: string[], profileId: string | null) : Promise<Result<AnalyzedGameEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("analysis_db_get_analyzed_games_bulk", { gameIds, profileId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async dashboardGetAnalyzeAllCounts(req: AnalyzeAllCountsRequest) : Promise<Result<AnalyzeAllCountsResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("dashboard_get_analyze_all_counts", { req }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async dashboardGetGamesHistoryRows(req: GamesHistoryRequest) : Promise<Result<GamesHistoryResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("dashboard_get_games_history_rows", { req }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async dashboardSearchProfileOpponents(profileId: string, query: string, profileUsernames: string[]) : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("dashboard_search_profile_opponents", { profileId, query, profileUsernames }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async dashboardResolveProfileDbGameId(profileId: string, kind: GamesHistoryKind, gameKey: string) : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("dashboard_resolve_profile_db_game_id", { profileId, kind, gameKey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async plannerBuildVariantBook(req: PlannerBuildBookRequest) : Promise<Result<VariantBook, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("planner_build_variant_book", { req }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async plannerBuildVariantPgn(req: PlannerBuildPgnRequest) : Promise<Result<PlannerBuildPgnResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("planner_build_variant_pgn", { req }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openExternalLink(url: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_external_link", { url }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async computePawnStructures(file: string, options: PawnStructureOptions) : Promise<Result<PawnStructureStat[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("compute_pawn_structures", { file, options }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Calculate game statistics from filtered games
 */
async calculatePlayerGameStats(siteStatsData: SiteStatsData[], filters: PlayerStatsFilters) : Promise<Result<GameStats, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("calculate_player_game_stats", { siteStatsData, filters }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Calculate ELO buckets from game data
 */
async calculatePlayerEloBuckets(siteStatsData: SiteStatsData[]) : Promise<EloBucket[]> {
    return await TAURI_INVOKE("calculate_player_elo_buckets", { siteStatsData });
},
/**
 * Calculate the sidebar model for PlayerSidebarCard (style + ELO summary).
 */
async calculatePlayerSidebarModel(siteStatsData: SiteStatsData[]) : Promise<PlayerSidebarModel> {
    return await TAURI_INVOKE("calculate_player_sidebar_model", { siteStatsData });
},
/**
 * Calculate opening statistics
 */
async calculatePlayerOpeningsStats(siteStatsData: SiteStatsData[], filters: PlayerStatsFilters, color: boolean) : Promise<OpeningStats[]> {
    return await TAURI_INVOKE("calculate_player_openings_stats", { siteStatsData, filters, color });
},
/**
 * Calculate rating timeline
 */
async calculatePlayerRatingTimeline(siteStatsData: SiteStatsData[], filters: PlayerStatsFilters) : Promise<Result<RatingTimeline, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("calculate_player_rating_timeline", { siteStatsData, filters }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Calculate ELO domain for rating chart
 */
async calculatePlayerEloDomain(ratingTimeline: RatingTimeline) : Promise<EloDomain | null> {
    return await TAURI_INVOKE("calculate_player_elo_domain", { ratingTimeline });
},
/**
 * Merge site stats data from multiple sources
 */
async mergePlayerSiteStats(siteStatsDataList: SiteStatsData[]) : Promise<SiteStatsData[]> {
    return await TAURI_INVOKE("merge_player_site_stats", { siteStatsDataList });
},
/**
 * Fill missing months in monthly data
 */
async fillMissingMonthsData(data: MonthData[]) : Promise<MonthData[]> {
    return await TAURI_INVOKE("fill_missing_months_data", { data });
},
/**
 * Merge years in monthly data
 */
async mergeYearsData(data: MonthData[]) : Promise<MonthData[]> {
    return await TAURI_INVOKE("merge_years_data", { data });
},
/**
 * Calculate earliest date based on date range
 */
async calculateEarliestDateFromRange(dateRange: DateRange, ratingDates: bigint[]) : Promise<bigint | null> {
    return await TAURI_INVOKE("calculate_earliest_date_from_range", { dateRange, ratingDates });
},
async getAccountSyncState(dbPath: string, accountKey: string, platform: string) : Promise<Result<AccountSyncState | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_account_sync_state", { dbPath, accountKey, platform }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async upsertAccountSyncState(dbPath: string, syncState: AccountSyncState) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("upsert_account_sync_state", { dbPath, syncState }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async markAccountSyncBatchComplete(dbPath: string, accountKey: string, platform: string, batchId: string, completedAtMs: bigint) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mark_account_sync_batch_complete", { dbPath, accountKey, platform, batchId, completedAtMs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listAccountSyncCompletedBatches(dbPath: string, accountKey: string, platform: string) : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_account_sync_completed_batches", { dbPath, accountKey, platform }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAccountImportStats(profileId: string, platform: string, username: string) : Promise<Result<AccountImportStats, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_account_import_stats", { profileId, platform, username }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async syncAccountGamesToProfileDb(profileId: string, profileTitle: string, platform: string, username: string, token: string | null) : Promise<Result<AccountSyncResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("sync_account_games_to_profile_db", { profileId, profileTitle, platform, username, token }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getLichessAccount(token: string | null, username: string | null) : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_lichess_account", { token, username }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getChesscomAccount(username: string) : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_chesscom_account", { username }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createLichessTournament(input: LichessTournamentCreateRequest) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_lichess_tournament", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async upsertManagedEvent(file: string, payload: CreateManagedEventPayload) : Promise<Result<Event, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("upsert_managed_event", { file, payload }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listManagedEvents(file: string) : Promise<Result<Event[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_managed_events", { file }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteManagedEvent(file: string, eventId: number) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_managed_event", { file, eventId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addEventGamesFromPgn(file: string, eventId: number, pgn: string) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_event_games_from_pgn", { file, eventId, pgn }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createEventGame(file: string, eventId: number, payload: CreateEventGamePayload) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_event_game", { file, eventId, payload }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
accountSyncProgress: AccountSyncProgress,
bestMovesPayload: BestMovesPayload,
databaseProgress: DatabaseProgress,
downloadProgress: DownloadProgress,
reportProgress: ReportProgress
}>({
accountSyncProgress: "account-sync-progress",
bestMovesPayload: "best-moves-payload",
databaseProgress: "database-progress",
downloadProgress: "download-progress",
reportProgress: "report-progress"
})

/** user-defined constants **/



/** user-defined types **/

export type AccountImportStats = { last_game_utc_ms?: bigint | null; count: bigint }
export type AccountSyncProgress = { profile_id: string; account_key: string; platform: string; total_batches: bigint; completed_batches: bigint; current_batch: bigint; batch_label: string; cooldown_seconds?: bigint | null }
export type AccountSyncResult = { 
/**
 * Number of new games imported during this sync session.
 * Computed as (post_count - pre_count) for the account.
 */
imported_games: bigint }
export type AccountSyncState = { account_key: string; platform: string; cursor_until_ms: bigint | null; since_ms?: bigint | null; mode?: string; total_batches: bigint; completed_batches: bigint; running: boolean; updated_at_ms: bigint }
/**
 * Options for full-game analysis (FEN, moves, novelty annotation, etc).
 */
export type AnalysisOptions = { fen: string; moves: string[]; annotateNovelties: boolean; referenceDb: string | null; reversed: boolean }
export type AnalyzeAllCountsRequest = { profileId: string; gameHistoryLimit: number; eventFilterId: number | null; selectedOpponentId: number | null; timeControlCategory: string | null; profileUsernames: string[]; target: AnalyzeAllTarget }
export type AnalyzeAllCountsResponse = { total: number; analyzed: number; unanalyzed: number }
export type AnalyzeAllTarget = "local" | "chesscom" | "lichess" | "all"
export type AnalyzedGameEntry = { profile_id: string; game_id: string; analyzed_pgn: string }
/**
 * Best-move line from engine output, including PV, score, and stats.
 */
export type BestMoves = { nodes: number; depth: number; score: Score; uciMoves: string[]; sanMoves: string[]; multipv: number; nps: number }
/**
 * Event payload for best-move updates (emitted to frontend).
 */
export type BestMovesPayload = { bestLines: BestMoves[]; engine: string; tab: string; fen: string; moves: string[]; progress: number }
export type BookEdge = { from: bigint; to: bigint; uci: string; prob: number; kind: EdgeKind; evCpFromOurPerspective: number | null; predictedProb: number | null }
export type BookNode = { id: bigint; fen: string; plyFromRoot: bigint; sideToMove: PlayerColor; reachProb: number }
export type BuildVariantsTreeRequest = { root: VariantsTreeNodeDto; startPath: number[]; orientation: string; is960: boolean; dbType: string; localDbPath?: string | null; lichessOptions?: LichessGamesOptionsDto | null; masterOptions?: MasterGamesOptionsDto | null; mode: string; engine?: EngineRequestDto | null; engineMs: number; coverage: number; minMoves: number; depth: number }
export type BuildVariantsTreeResponse = { lines: LineDto[] }
export type CreateEventGamePayload = { white: string; black: string; date?: string | null; round?: string | null; result: Outcome }
export type CreateManagedEventPayload = { name: string; eventType: ManagedEventType; location?: string | null; startDate?: string | null; endDate?: string | null; timeControl?: string | null }
export type DatabaseInfo = { title: string; description: string; player_count: number; event_count: number; game_count: number; storage_size: bigint; filename: string; indexed: boolean }
export type DatabaseProgress = { id: string; progress: number }
export type DateRange = "SevenDays" | "ThirtyDays" | "NinetyDays" | "OneYear" | "All"
export type DownloadProgress = { progress: number; id: string; finished: boolean }
export type EdgeKind = "ourMove" | "opponentMove"
export type EloBucket = { value: string; label: string }
export type EloDomain = { min: number; max: number }
/**
 * UCI engine configuration (name and available options).
 */
export type EngineConfig = { name: string; options: UciOptionConfig[] }
/**
 * Limits passed to the engine. Use either depth or time (or both).
 */
export type EngineLimits = { depth: number | null; timeMs: number | null }
/**
 * Log entry for engine GUI or engine output.
 */
export type EngineLog = { type: "gui"; value: string } | { type: "engine"; value: string }
/**
 * UCI engine option (name-value pair).
 */
export type EngineOption = { name: string; value: string }
/**
 * Options for configuring engine analysis (FEN, moves, extra UCI options).
 */
export type EngineOptions = { fen: string; moves: string[]; extraOptions: EngineOption[] }
export type EngineRequestDto = { name: string; path: string; extraOptions?: EngineOption[] }
export type Event = { id: number; name: string | null; event_type?: string | null; location?: string | null; start_date?: string | null; end_date?: string | null; time_control?: string | null }
export type FidePlayer = { fideid: number; name: string; country: string; sex: string; title: string | null; w_title: string | null; o_title: string | null; foa_title: string | null; rating: number | null; games: number | null; k: number | null; rapid_rating: number | null; rapid_games: number | null; rapid_k: number | null; blitz_rating: number | null; blitz_games: number | null; blitz_k: number | null; birthday: number | null; flag: string | null }
export type FileMetadata = { last_modified: bigint; size: bigint; is_dir: boolean; is_readonly: boolean }
export type GameOutcome = "Won" | "Drawn" | "Lost"
export type GameQueryJs = { options?: QueryOptions<GameSort> | null; 
/**
 * Optional limit for number of game details to load (stats are always full)
 * Used to fetch small preview (e.g., 10) and then on-demand up to 1000
 * Using u64 instead of usize for better bigint compatibility with TypeScript
 * Serialized as string to handle bigint in JSON
 */
game_details_limit?: bigint | null; player1?: number | null; player2?: number | null; tournament_id?: number | null; start_date?: string | null; end_date?: string | null; range1?: [number, number] | null; range2?: [number, number] | null; sides?: Sides | null; outcome?: string | null; position?: PositionQueryJs | null; wanted_result?: string | null; 
/**
 * Optional time control category filter.
 * Expected values: ultra_bullet, bullet, blitz, rapid, classical, correspondence, daily.
 */
time_control_category?: string | null }
export type GameSort = "id" | "date" | "whiteElo" | "blackElo" | "averageElo" | "ply_count"
export type GameStats = { total: bigint; won: bigint; draw: bigint; lost: bigint; data_per_month: MonthData[]; unknown_count: bigint }
export type GameStatsEntry = { profileId: string; gameId: string; accuracy: number; acpl: number; estimatedElo: bigint | null }
export type GamesHistoryKind = "local" | "chesscom" | "lichess"
export type GamesHistoryRequest = { profileId: string; gameHistoryLimit: number; page: number; pageSize: number; eventFilterId: number | null; selectedOpponentId: number | null; opponentContains: string | null; timeControlCategory: string | null; resultFilter: string | null; sortBy: string | null; sortDirection: string | null; profileUsernames: string[] }
export type GamesHistoryResponse = { rows: GamesHistoryRow[]; totalCount: number }
export type GamesHistoryRow = { kind: GamesHistoryKind; 
/**
 * UI identifier (Chess.com URL, Lichess id, or local id).
 * This is stable for rendering & actions like "open URL" or "favorite".
 */
gameKey: string; 
/**
 * Key used to LEFT JOIN with analysis.db3 (`game_analysis.game_id`).
 * For profile DB games this is `Games.ID` (as string). For local games it's the local id.
 */
analysisGameId: string; 
/**
 * For online games: URL for chess.com, `https://lichess.org/<id>` for lichess. Null for local.
 */
externalUrl: string | null; opponent: string; color: string; 
/**
 * "win" | "loss" | "draw" | "unknown"
 */
outcome: string; 
/**
 * Original PGN if available (may be overwritten by analyzed PGN if present).
 */
pgn: string | null; accuracy: number | null; acpl: number | null; estimatedElo: bigint | null; 
/**
 * Approximate number of full moves.
 */
moves: number; timeControl: string | null; timeControlCategory: string | null; timestampMs: bigint; eventId: number | null; eventName: string | null; isAnalyzed: boolean }
export type GeneratePuzzleVariantsResponse = { pgn: string; count: bigint }
/**
 * Engine search mode (depth, time, nodes, etc).
 */
export type GoMode = { t: "PlayersTime"; c: PlayersTime } | { t: "Depth"; c: number } | { t: "Time"; c: number } | { t: "Nodes"; c: number } | { t: "Infinite" }
export type LichessGamesOptionsDto = { variant?: string | null; speeds?: string[] | null; ratings?: number[] | null; 
/**
 * Serialized from JS Date as ISO string (or omitted).
 */
since?: string | null; until?: string | null; moves?: number | null; topGames?: number | null; recentGames?: number | null; player?: string | null; color: string }
export type LichessTournamentCreateRequest = { token: string; 
/**
 * Form-encoded fields (key/value), same as URLSearchParams in the frontend.
 */
form: ([string, string])[] }
export type LineDto = { moves: MoveSpecDto[] }
export type ManagedEventType = "otb_tournament" | "online_tournament" | "league"
export type MasterGamesOptionsDto = { since?: string | null; until?: string | null; moves?: number | null; topGames?: number | null }
/**
 * Match inputs we care about: when, time-control, colors, and starting position.
 */
export type MatchContext = { 
/**
 * Match start datetime (UTC) as milliseconds since epoch.
 */
matchStartUtcMs: bigint; 
/**
 * Time control string (e.g. "300+0", "180+2").
 */
timeControl: string; 
/**
 * Our Elo (used to bucket the opponent model context).
 */
ourElo: number; 
/**
 * Target player id (from profile DB Players.ID).
 */
targetPlayerId: bigint; 
/**
 * Our color for the match.
 */
ourColor: PlayerColor; 
/**
 * Starting position (FEN) or "startpos".
 */
startFen: string }
export type MonthData = { name: string; count: bigint }
/**
 * Analysis result for a single move/position.
 */
export type MoveAnalysis = { best: BestMoves[]; novelty: boolean; is_sacrifice: boolean }
export type MoveSpecDto = { 
/**
 * We now prefer SAN for stability with the frontend tree store.
 * (Frontend still supports SAN or UCI, but SAN is the default here.)
 */
value: string; 
/**
 * "db" | "engine"
 */
source?: string | null; 
/**
 * Raw DB stats when the move is sourced from a database.
 */
white?: number | null; black?: number | null; draws?: number | null; total?: number | null }
export type NormalizedGame = { id: number; fen: string; event: string; event_id: number; site: string; site_id: number; date?: string | null; time?: string | null; round?: string | null; white: string; white_id: number; white_elo?: number | null; black: string; black_id: number; black_elo?: number | null; result: Outcome; time_control?: string | null; eco?: string | null; ply_count?: number | null; moves: string }
export type OpeningInfo = { eco: string; opening: string; variation: string }
export type OpeningStats = { name: string; games: bigint; won: bigint; draw: bigint; lost: bigint }
/**
 * Opening tag option with technical value and friendly label
 */
export type OpeningTagOption = { value: string; label: string }
export type OutOpening = { name: string; fen: string }
export type Outcome = "1-0" | "0-1" | "1/2-1/2" | "*"
export type PackageManagerResult = { success: boolean; stdout: string; stderr: string }
export type PawnStructureGame = { game_id: number; white: string; black: string; white_elo: number | null; black_elo: number | null; result: string; fen: string }
export type PawnStructureOptions = { playerIds: number[]; colorFilter: string; platformFilter: string; timeControlFilter: string; opponentEloBucket: string; 
/**
 * Date range filter: "SevenDays" | "ThirtyDays" | "NinetyDays" | "OneYear" | "All" | null
 * If null or "All", no date filtering is applied.
 */
dateRange?: string | null; moveNumber: number; playerColor: string; pawnStructureMode: string; 
/**
 * Optional pawn-structure motif filters, applied server-side.
 * When empty, no motif filtering is applied.
 */
structureFilters?: string[]; 
/**
 * Optional named pawn-structure filters (e.g. "carlsbad", "najdorf").
 * OR semantics within the list: if any selected structure matches, the stat is kept.
 */
structureNameFilters?: string[] }
export type PawnStructureStat = { structure: string; frequency: number; win_rate: number; sample_fen: string | null; games: PawnStructureGame[] }
/**
 * Planning controls and safety bounds.
 */
export type PlanOptions = { horizonPlies: bigint; opponentTopK: bigint; minBranchProb: number; maxNodes: bigint; ourMultipv: bigint; quickEvalLimits: EngineLimits; candidateLimits: EngineLimits; 
/**
 * Controls how quickly we fall back from exact-state evidence to backoff evidence.
 * Larger values => rely more on backoff unless exact has strong support.
 */
backoffK: number; 
/**
 * Controls how strongly we smooth probabilities toward the prior distribution (Dirichlet prior strength).
 * 0 => no prior smoothing (pure MLE on observed counts). Larger values => more conservative.
 */
smoothingAlpha: number }
export type PlannerBuildBookRequest = { profileId: string; enginePath: string; 
/**
 * Extra UCI options to apply (e.g. Hash, SyzygyPath). MultiPV is managed by the planner.
 */
uciOptions: EngineOption[]; ctx: MatchContext; opts: PlanOptions }
export type PlannerBuildPgnRequest = { profileId: string; enginePath: string; 
/**
 * Extra UCI options to apply (e.g. Hash, SyzygyPath). MultiPV is managed by the planner.
 */
uciOptions: EngineOption[]; ctx: MatchContext; opts: PlanOptions }
export type PlannerBuildPgnResponse = { pgn: string }
export type PlatformFilter = "All" | "Lichess" | "ChessCom"
export type PlatformInfo = { key: string; label: string; stroke: string }
export type Player = { id: number; name: string | null; elo: number | null }
export type PlayerColor = "white" | "black"
export type PlayerGameInfo = { site_stats_data: SiteStatsData[] }
export type PlayerQuery = { options: QueryOptions<PlayerSort>; name?: string | null; range?: [number, number] | null }
export type PlayerSidebarEloBlock = { 
/**
 * Display label (e.g. "Lichess", "Chess.com")
 */
platform: string; 
/**
 * One row per platform (when multiple platforms exist) OR one row per account (when a single platform has multiple accounts).
 */
rows: PlayerSidebarEloRow[] }
export type PlayerSidebarEloRow = { label: string; bullet: string; blitz: string; rapid: string }
export type PlayerSidebarModel = { has_data: boolean; style: PlayerStyleLabel; elo: PlayerSidebarEloBlock[] }
export type PlayerSort = "id" | "name" | "elo"
export type PlayerStatsFilters = { platform: PlatformFilter; time_control: TimeControlFilter; opponent_elo_bucket: string | null; date_range: DateRange | null }
export type PlayerStyleLabel = { label: string; description: string; color: string }
/**
 * Player time controls for GoMode::PlayersTime.
 */
export type PlayersTime = { white: number; black: number; winc: number; binc: number }
export type PositionQueryJs = { fen: string; type_: string }
export type PositionStats = { move: string; white: number; draw: number; black: number }
export type Puzzle = { id: number; fen: string; moves: string; rating: number; rating_deviation: number; popularity: number; nb_plays: number; themes: string | null; game_url: string | null; opening_tags: string | null }
/**
 * Information about a puzzle database
 */
export type PuzzleDatabaseInfo = { 
/**
 * The title of the puzzle database (derived from filename)
 */
title: string; 
/**
 * Description of the puzzle database (currently not populated)
 * TODO: Consider adding a way to store and retrieve database descriptions
 */
description: string; 
/**
 * Number of puzzles in the database
 */
puzzleCount: number; 
/**
 * Size of the database file in bytes
 */
storageSize: bigint; 
/**
 * Full path to the database file
 */
path: string }
export type PuzzleTreeNodeDto = { fen: string; san?: string | null; children?: PuzzleTreeNodeDto[] }
export type QueryOptions<SortT> = { skipCount: boolean; page?: number | null; pageSize?: number | null; sort: SortT; direction: SortDirection }
export type QueryResponse<T> = { data: T; count: number | null }
export type RatingDataPoint = { date: bigint; chesscom: number | null; lichess: number | null }
export type RatingTimeline = { data: RatingDataPoint[]; dates: bigint[]; platforms: PlatformInfo[] }
/**
 * Event payload for reporting analysis progress.
 */
export type ReportProgress = { progress: number; id: string; finished: boolean }
/**
 * UCI score representation for UI and analysis.
 */
export type Score = { value: ScoreValue; wdl: [number, number, number] | null }
/**
 * UCI score value (centipawns or mate).
 */
export type ScoreValue = { type: "cp"; value: number } | { type: "mate"; value: number }
export type Sides = "BlackWhite" | "WhiteBlack" | "Any"
export type SiteStatsData = { site: string; player: string; data: StatsData[] }
export type SortDirection = "asc" | "desc"
export type StatsData = { date: string; is_player_white: boolean; player_elo: number; opponent_elo: number | null; result: GameOutcome; time_control: string; opening: string }
export type StoredGameStats = { accuracy: number; acpl: number; estimatedElo: bigint | null }
/**
 * Theme group containing a category name and its themes
 */
export type ThemeGroup = { group: string; items: ThemeOption[] }
/**
 * Theme option with technical value and friendly label
 */
export type ThemeOption = { value: string; label: string }
export type TimeControlFilter = "Any" | "Bullet" | "Blitz" | "Rapid" | "Classical"
export type Token = { type: "ParenOpen" } | { type: "ParenClose" } | { type: "Comment"; value: string } | { type: "San"; value: string } | { type: "Header"; value: { tag: string; value: string } } | { type: "Nag"; value: string } | { type: "Outcome"; value: string }
export type TournamentQuery = { options: QueryOptions<TournamentSort>; name: string | null }
export type TournamentSort = "id" | "name" | "start_date" | "end_date"
/**
 * Represents a UCI option definition.
 */
export type UciOptionConfig = 
/**
 * The option of type `check` (a boolean).
 */
{ type: "check"; value: { name: string; default: boolean | null } } | 
/**
 * The option of type `spin` (a signed integer).
 */
{ type: "spin"; value: { name: string; default: bigint | null; min: bigint | null; max: bigint | null } } | 
/**
 * The option of type `combo` (a list of strings).
 */
{ type: "combo"; value: { name: string; default: string | null; var: string[] } } | 
/**
 * The option of type `button` (an action).
 */
{ type: "button"; value: { name: string } } | 
/**
 * The option of type `string` (a string, unsurprisingly).
 */
{ type: "string"; value: { name: string; default: string | null } }
export type UpdateGame = { fen: string; event: string; site: string; date?: string | null; time?: string | null; round?: string | null; white: string; white_elo?: number | null; black: string; black_elo?: number | null; result: Outcome; time_control?: string | null; eco?: string | null; ply_count?: number | null; moves: string }
export type VariantBook = { rootNodeId: bigint; nodes: BookNode[]; edges: BookEdge[] }
export type VariantPosition = { fen: string; engine: string; recommended_move: string; ms: bigint }
export type VariantsTreeNodeDto = { fen: string; san?: string | null; children?: VariantsTreeNodeDto[] }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
