/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VariantsRouteImport } from './routes/variants'
import { Route as TournamentsRouteImport } from './routes/tournaments'
import { Route as PuzzlesRouteImport } from './routes/puzzles'
import { Route as ProfilesRouteImport } from './routes/profiles'
import { Route as PlayRouteImport } from './routes/play'
import { Route as FilesRouteImport } from './routes/files'
import { Route as EventsRouteImport } from './routes/events'
import { Route as EnginesRouteImport } from './routes/engines'
import { Route as ChessbaseRouteImport } from './routes/chessbase'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as DatabasesIndexRouteImport } from './routes/databases/index'
import { Route as SettingsKeyboardShortcutsRouteImport } from './routes/settings/keyboard-shortcuts'
import { Route as DatabasesDatabaseIdRouteImport } from './routes/databases/$databaseId'

const VariantsRoute = VariantsRouteImport.update({
  id: '/variants',
  path: '/variants',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsRoute = TournamentsRouteImport.update({
  id: '/tournaments',
  path: '/tournaments',
  getParentRoute: () => rootRouteImport,
} as any)
const PuzzlesRoute = PuzzlesRouteImport.update({
  id: '/puzzles',
  path: '/puzzles',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilesRoute = ProfilesRouteImport.update({
  id: '/profiles',
  path: '/profiles',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const EnginesRoute = EnginesRouteImport.update({
  id: '/engines',
  path: '/engines',
  getParentRoute: () => rootRouteImport,
} as any)
const ChessbaseRoute = ChessbaseRouteImport.update({
  id: '/chessbase',
  path: '/chessbase',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const DatabasesIndexRoute = DatabasesIndexRouteImport.update({
  id: '/databases/',
  path: '/databases/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsKeyboardShortcutsRoute =
  SettingsKeyboardShortcutsRouteImport.update({
    id: '/keyboard-shortcuts',
    path: '/keyboard-shortcuts',
    getParentRoute: () => SettingsRouteRoute,
  } as any)
const DatabasesDatabaseIdRoute = DatabasesDatabaseIdRouteImport.update({
  id: '/databases/$databaseId',
  path: '/databases/$databaseId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/accounts': typeof AccountsRoute
  '/analysis': typeof AnalysisRoute
  '/chessbase': typeof ChessbaseRoute
  '/engines': typeof EnginesRoute
  '/events': typeof EventsRoute
  '/files': typeof FilesRoute
  '/play': typeof PlayRoute
  '/profiles': typeof ProfilesRoute
  '/puzzles': typeof PuzzlesRoute
  '/tournaments': typeof TournamentsRoute
  '/variants': typeof VariantsRoute
  '/databases/$databaseId': typeof DatabasesDatabaseIdRoute
  '/settings/keyboard-shortcuts': typeof SettingsKeyboardShortcutsRoute
  '/databases/': typeof DatabasesIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/analysis': typeof AnalysisRoute
  '/chessbase': typeof ChessbaseRoute
  '/engines': typeof EnginesRoute
  '/events': typeof EventsRoute
  '/files': typeof FilesRoute
  '/play': typeof PlayRoute
  '/profiles': typeof ProfilesRoute
  '/puzzles': typeof PuzzlesRoute
  '/tournaments': typeof TournamentsRoute
  '/variants': typeof VariantsRoute
  '/databases/$databaseId': typeof DatabasesDatabaseIdRoute
  '/settings/keyboard-shortcuts': typeof SettingsKeyboardShortcutsRoute
  '/databases': typeof DatabasesIndexRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/accounts': typeof AccountsRoute
  '/analysis': typeof AnalysisRoute
  '/chessbase': typeof ChessbaseRoute
  '/engines': typeof EnginesRoute
  '/events': typeof EventsRoute
  '/files': typeof FilesRoute
  '/play': typeof PlayRoute
  '/profiles': typeof ProfilesRoute
  '/puzzles': typeof PuzzlesRoute
  '/tournaments': typeof TournamentsRoute
  '/variants': typeof VariantsRoute
  '/databases/$databaseId': typeof DatabasesDatabaseIdRoute
  '/settings/keyboard-shortcuts': typeof SettingsKeyboardShortcutsRoute
  '/databases/': typeof DatabasesIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/accounts'
    | '/analysis'
    | '/chessbase'
    | '/engines'
    | '/events'
    | '/files'
    | '/play'
    | '/profiles'
    | '/puzzles'
    | '/tournaments'
    | '/variants'
    | '/databases/$databaseId'
    | '/settings/keyboard-shortcuts'
    | '/databases/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/analysis'
    | '/chessbase'
    | '/engines'
    | '/events'
    | '/files'
    | '/play'
    | '/profiles'
    | '/puzzles'
    | '/tournaments'
    | '/variants'
    | '/databases/$databaseId'
    | '/settings/keyboard-shortcuts'
    | '/databases'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/accounts'
    | '/analysis'
    | '/chessbase'
    | '/engines'
    | '/events'
    | '/files'
    | '/play'
    | '/profiles'
    | '/puzzles'
    | '/tournaments'
    | '/variants'
    | '/databases/$databaseId'
    | '/settings/keyboard-shortcuts'
    | '/databases/'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
  AccountsRoute: typeof AccountsRoute
  AnalysisRoute: typeof AnalysisRoute
  ChessbaseRoute: typeof ChessbaseRoute
  EnginesRoute: typeof EnginesRoute
  EventsRoute: typeof EventsRoute
  FilesRoute: typeof FilesRoute
  PlayRoute: typeof PlayRoute
  ProfilesRoute: typeof ProfilesRoute
  PuzzlesRoute: typeof PuzzlesRoute
  TournamentsRoute: typeof TournamentsRoute
  VariantsRoute: typeof VariantsRoute
  DatabasesDatabaseIdRoute: typeof DatabasesDatabaseIdRoute
  DatabasesIndexRoute: typeof DatabasesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/variants': {
      id: '/variants'
      path: '/variants'
      fullPath: '/variants'
      preLoaderRoute: typeof VariantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments': {
      id: '/tournaments'
      path: '/tournaments'
      fullPath: '/tournaments'
      preLoaderRoute: typeof TournamentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/puzzles': {
      id: '/puzzles'
      path: '/puzzles'
      fullPath: '/puzzles'
      preLoaderRoute: typeof PuzzlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiles': {
      id: '/profiles'
      path: '/profiles'
      fullPath: '/profiles'
      preLoaderRoute: typeof ProfilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engines': {
      id: '/engines'
      path: '/engines'
      fullPath: '/engines'
      preLoaderRoute: typeof EnginesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chessbase': {
      id: '/chessbase'
      path: '/chessbase'
      fullPath: '/chessbase'
      preLoaderRoute: typeof ChessbaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/databases/': {
      id: '/databases/'
      path: '/databases'
      fullPath: '/databases/'
      preLoaderRoute: typeof DatabasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/keyboard-shortcuts': {
      id: '/settings/keyboard-shortcuts'
      path: '/keyboard-shortcuts'
      fullPath: '/settings/keyboard-shortcuts'
      preLoaderRoute: typeof SettingsKeyboardShortcutsRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/databases/$databaseId': {
      id: '/databases/$databaseId'
      path: '/databases/$databaseId'
      fullPath: '/databases/$databaseId'
      preLoaderRoute: typeof DatabasesDatabaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SettingsRouteRouteChildren {
  SettingsKeyboardShortcutsRoute: typeof SettingsKeyboardShortcutsRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsKeyboardShortcutsRoute: SettingsKeyboardShortcutsRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  AccountsRoute: AccountsRoute,
  AnalysisRoute: AnalysisRoute,
  ChessbaseRoute: ChessbaseRoute,
  EnginesRoute: EnginesRoute,
  EventsRoute: EventsRoute,
  FilesRoute: FilesRoute,
  PlayRoute: PlayRoute,
  ProfilesRoute: ProfilesRoute,
  PuzzlesRoute: PuzzlesRoute,
  TournamentsRoute: TournamentsRoute,
  VariantsRoute: VariantsRoute,
  DatabasesDatabaseIdRoute: DatabasesDatabaseIdRoute,
  DatabasesIndexRoute: DatabasesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
